language: generic
branches:
  # Travis is configured to build branches and PRs. Need to
  # restrict branch builds to just master branch, otherwise
  # PRs from same repo are built twice.
  only:
    - master
script:
  - scripts/travis_tests
deploy:
  provider: s3
  bucket: "aws-experiments"
  region: "eu-west-1"
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  upload-dir: "artifacts/spring-experiments"
  local_dir: "build/libs/"
  skip_cleanup: true
  on:
    branch: master