Resources:
  Function:
    Type: AWS::Serverless::Function
    Metadata:
      SkipBuild: True
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: uk.me.jeremygreen.springexperiments.StreamLambdaHandler
      CodeUri: /home/jg210/repo/jg210/spring-experiments/build/libs/spring-experiments-1.0-aws.jar
      Runtime: java17
      Architectures:
        - x86_64
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: get

      
