name: checks

on: push

jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      checks: write

    steps:
    - uses: actions/checkout@v4.1.1
    
    - name: JDK
      uses: actions/setup-java@v4.0.0
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    
    - uses: actions/setup-node@v4.0.1
      with:
        node-version-file: '.node-version'

    - uses: actions/setup-python@v5.0.0
      with:
        cache: 'pip'

    - name: setup gradle
      uses: gradle/actions/setup-gradle@v3

    - name: local bin/setup script
      run: ./bin/setup

    - name: npm install
      working-directory: src/frontend
      run: |
        . environment
        npm ci

    - name: npm run ci
      working-directory: src/frontend
      run: |
        . environment
        npm run ci

    - name: npm run build
      working-directory: src/frontend
      run: |
        . environment
        npm run build
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_DSN_SPRING_EXPERIMENTS: ${{ secrets.SENTRY_DSN_SPRING_EXPERIMENTS }}

    - name: gradle assemble
      run: ./gradlew --scan assemble

    # Store jars as artifacts for debugging.
    - name: archive jars
      uses: actions/upload-artifact@v4.3.0
      with:
        name: jars
        path: |
          build/libs/*.jar
    
    - name: gradle check
      run: ./gradlew --scan check
      env:
        SENTRY_DSN_SPRING_EXPERIMENTS: ${{ secrets.SENTRY_DSN_SPRING_EXPERIMENTS }}

    - name: test teport - native junit
      uses: dorny/test-reporter@v1.8.0
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: native junit
        path: build/test-results/test/*.xml
        reporter: java-junit

    - name: test teport - vitest
      uses: dorny/test-reporter@v1.8.0
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: vitest
        path: src/frontend/junit-report.xml
        reporter: jest-junit

    - name: archive gradle build reports
      uses: actions/upload-artifact@v4.3.0
      if: success() || failure()
      with:
        name: build reports
        path: build/reports/

    - name: cypress end-to-end tests - spring boot jar
      run: |
        . environment
        java -jar build/libs/spring-experiments-1.0.jar &
        trap "kill $!" EXIT
        wait-on -t 60s http://localhost:8080
        TERM=linux cypress run --config baseUrl=http://localhost:8080 --project src/frontend

    - name: cypress end-to-end tests - sam local start-api
      run: |
        . environment
        logFile="${RUNNER_TEMP}/sam_logs.txt"
        echo "starting server, logging to: ${logFile}"
        sam local start-api --warm-containers EAGER --debug > "${logFile}" 2>&1 &
        trap "kill $!" EXIT
        wait-on -t 60s http://localhost:3000
        TERM=linux cypress run --config baseUrl=http://localhost:3000 --project src/frontend

    - name: archive sam local start-api logs
      uses: actions/upload-artifact@v4.3.0
      if: success() || failure()
      with:
        name: sam_logs.txt
        path: ${{ runner.temp }}/sam_logs.txt

    # Publish to S3 for deployment
    - name: gradle publish
      if: ${{ github.ref == 'refs/heads/master' }}
      run: ./gradlew --scan publish
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
